<?php

namespace BB\LivreurBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LivreurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLivreurs($page, $nbPerPage)
    {
      $query = $this->createQueryBuilder('a')
        ->orderBy('a.nom, a.prenom', 'ASC')
        ->getQuery()
      ;
      $query
        // On définit le livreur à partir de laquelle commencer la liste
        ->setFirstResult(($page-1) * $nbPerPage)
        // Ainsi que le nombre à afficher sur une page
        ->setMaxResults($nbPerPage)
      ;
      // On retourne l'objet Paginator correspondant à la requête construite
      return new Paginator($query, true);
    }
}
